### ISSUE TITLE
Song Not The Right Tempo

### ISSUE THREAD

**Issue by aidendesjarlais** [TOG11/DotPianoMidiPlayer#1]
Working on adding a tempo setting, however first i need to see if dotpiano even controls that. Ill let you know more in a couple days on how its going.

**Comment by aidendesjarlais** [comment]
Great news! Turns out DotPiano controls the tempo and ppq of the midi. update soon.

**Comment by aidendesjarlais** [comment]
Release will be soon, working on config files. going to see if i can add a ppq setting, if not then ill just release without it. tempo setting will be here soon!

**Comment by aidendesjarlais** [comment]
Cant add ppq setting, testing the tempo setting out. release within 5 minutes.

**Comment by TOG11** [comment]
Tempo Setting Added!

**Comment by aidendesjarlais** [comment]
Tempo Setting Added!
